name: Update Videos

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

concurrency:
  group: update-videos
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Feed Script
        run: node scripts/updateFeeds.js

      - name: Commit JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update cached videos
          file_pattern: videos.json